name: Terraform Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest
    steps:
      - name: Terraform format checking
        run: terraform fmt
  terraform-plan:
    name: Terraform planning
    runs-on: ubuntu-latest
    steps:
      - name: Terraform planning
        run: terraform plan
  terraform-apply:
    name: Terraform deploying
    runs-on: ubuntu-latest
    steps:
      - name: Terraform deploying
        run: terraform apply
