name: Terraform Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest
    steps:
      - name: Terraform format checking
        run: terraform fmt

  terraform-plan:
    name: Terraform planning
    runs-on: ubuntu-latest
    needs: terraform-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::156041410244:role/GithubActionsRole
      - name: Terraform init
        run: terraform init
      - name: Terraform planning
        run: terraform plan

  terraform-apply:
    name: Terraform deploying
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::156041410244:role/GithubActionsRole
      - name: Terraform init
        run: terraform init
      - name: Terraform deploying
        run: terraform apply
